// Notas da versão atual. Atualize esta lista a cada modificação relevante.
export const RELEASE_NOTES: string[] = [
  "Cabeçalho: ajustado o espaçamento do logo no canto superior esquerdo (não fica mais sobreposto ao título e à navegação).",
  "Novo cabeçalho unificado com navegação (Pedidos · Propostas · Admin) e menu do usuário com perfil e sair.",
  "Proposta comercial vira pedido com 1 clique (botão '→ Pedido' na lista e no editor).",
  "Botão WhatsApp em pedidos e propostas: envia o resumo pronto (cliente, itens, prazo e total).",
  "Pedidos: exportação do pedido atual em Excel e sugestão automática de clientes já atendidos (preenche código, telefone e prazo).",
  "Situações das propostas com selos coloridos (rascunho, enviada, aprovada, recusada).",
  "Tabela de preços atualizada (REV 0006.26 — setembro): 5 produtos novos (Riocare Baby 230ml/1L, Riohex Dermo Suave 30ml/100ml/1L) e novos preços do Riocare Gel de Arnica e Riozyme IV E Neutro.",

  "Propostas: nova opção 'somente preços' — oculta quantidades e valor total na tela e no PDF (tabela mostra apenas produto e valor unitário).",
  "PDF da proposta remodelado no formato do papel timbrado: data por extenso, saudação ao contato, apresentação, produtos, diferenciais, operação logística, compromisso e assinatura.",
  "Proposta: novos campos cidade, tratamento e nome do contato no cliente, e textos editáveis de diferenciais, logística e compromisso.",
  "Propostas: tabelas de preço seguem a mesma lógica dos pedidos (tabela complementar, bloqueio no Preço de Escolha, arredondamento por caixa).",
  "Novo módulo 'Propostas Comerciais': criar, salvar, duplicar e editar propostas com preços de qualquer tabela (editáveis) e gerar PDF profissional.",
  "Nova seção no admin: 'Histórico de preços' (/admin/prices) com filtro por código e período, mostrando preço anterior, novo, variação % e quem alterou.",
  "Tabela de preços atualizada conforme planilha HOSPITALAR (REV 0006.26 — agosto): 185 produtos com novos preços e impostos.",
  "5 produtos novos incluídos no catálogo (0510105423, 0530102057, 0530102058, 0530102059, 0530102060).",
  "Botão 'Excluir tudo' movido para dentro do card 'Dados do pedido' (canto direito, tamanho reduzido).",
  "Botão 'Excluir tudo' no cabeçalho para começar um novo pedido (limpa itens e dados do cabeçalho).",
  "Lista de prazos de pagamento padrão com opção de digitar manualmente.",
  "No mobile, clique na versão para ver as notas da release (popup).",
  "Campo de observações do pedido agora inicia com mensagem padrão editável.",
  "Bloqueio de redução de preço na tabela 'Preço de Escolha' (somente admins podem reduzir).",
  "Versão do app exibida no rodapé, atualizada automaticamente a cada build.",
  "Edição de pedido pelo Histórico agora atualiza o mesmo registro (sem duplicar), apenas mudando a data.",
  "Passe o mouse sobre a versão para ver as notas desta release.",
];
